// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solver.DataAccessLayer;

namespace Solver.APIClient.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    [Migration("20190728223251_AddProgram")]
    partial class AddProgram
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Solver.Entities.Models.Elements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<int>("Quantity");

                    b.Property<int?>("WorkingDaysId");

                    b.HasKey("Id");

                    b.HasIndex("WorkingDaysId");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("Solver.Entities.Models.ProgramConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnalyzeFileProvider");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Description");

                    b.Property<string>("ManagmentProvider");

                    b.HasKey("Id");

                    b.ToTable("ProgramConfigurations");
                });

            modelBuilder.Entity("Solver.Entities.Models.TrackLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("FileName");

                    b.Property<string>("Identification");

                    b.Property<bool>("IsValid");

                    b.HasKey("Id");

                    b.ToTable("TrackLogs");
                });

            modelBuilder.Entity("Solver.Entities.Models.TrackLogDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Message");

                    b.Property<int>("RowLine");

                    b.Property<int?>("TrackLogId");

                    b.HasKey("Id");

                    b.HasIndex("TrackLogId");

                    b.ToTable("TrackLogDetails");
                });

            modelBuilder.Entity("Solver.Entities.Models.WeightLastElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<int?>("ElementId");

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.ToTable("WeightLastElement");
                });

            modelBuilder.Entity("Solver.Entities.Models.WorkingDays", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<int>("DayToWork");

                    b.HasKey("Id");

                    b.ToTable("WorkingDays");
                });

            modelBuilder.Entity("Solver.Entities.Models.Elements", b =>
                {
                    b.HasOne("Solver.Entities.Models.WorkingDays", "WorkingDays")
                        .WithMany("Elements")
                        .HasForeignKey("WorkingDaysId");
                });

            modelBuilder.Entity("Solver.Entities.Models.TrackLogDetail", b =>
                {
                    b.HasOne("Solver.Entities.Models.TrackLog", "TrackLog")
                        .WithMany("TrackLogDetails")
                        .HasForeignKey("TrackLogId");
                });

            modelBuilder.Entity("Solver.Entities.Models.WeightLastElement", b =>
                {
                    b.HasOne("Solver.Entities.Models.Elements", "Element")
                        .WithMany("WeightLastElements")
                        .HasForeignKey("ElementId");
                });
#pragma warning restore 612, 618
        }
    }
}
